authentication/urls.py
from django.urls import path
from . import views

app_name = 'authenticate'

urlpatterns = [
    # Маршрут для регистрации и входа

    path('', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('register/wait/', views.RegistrationWaitView.as_view(), name='register-wait'),

    path('main-admin/profile/', views.admin_profile, name='admin-profile'),
    path('main-manager/profile/', views.manager_profile, name='manager-profile'),
    path('main-employee/profile/', views.employee_profile, name='employee-profile'),
    # path('main-manager/profile/', views.employee_profile, name='employee-profile'),

    path('logout/', views.logout_view, name='logout'),

]

management/urls.py
from django.urls import path
from . import views

from django.conf.urls import handler404
from .views import error_handler

app_name = 'management'

urlpatterns = [
    # Маршруты для администраторов
    path('admin-main/', views.admin_main, name='admin-main'),
    path('admin-managers/', views.admin_managers, name='admin-managers'),
    path('admin-employee/', views.admin_employee, name='admin-employee'),

    path('admin-manage/', views.admin_submit_completion_request, name='admin-manage'),
    path('admin-requests/', views.admin_requests, name='admin-requests'),
    path('admin-subpro/', views.admin_submit_completion_request, name='admin-submit-project'),
    path('admin-subtask/', views.admin_submit_task_completion_request, name='admin-submit-task'),

    path('admin-projects/', views.admin_projects, name='admin-projects'),

    # Маршруты для менеджеров

    path('manager-main/', views.manager_main, name='manager-main'),
    path('manager-emploee/', views.manager_employee, name='manager-employee'),
    path('manager-manage/', views.manager_create_task, name='manager-manage'),

    path('manager-manage-tasks/', views.manager_task_list, name='manager-task-list'),
    path('manager-manage-create-tasks/', views.manager_create_task, name='manager-task-create'),
    path('manager-main-delete-tasks/<int:task_id>/', views.manager_delete_task, name='manager-task-delete'),
    path('manager-main-update-tasks/<int:task_id>/', views.manager_update_task, name='manager-task-update'),
    path('manager-manage-create-project/', views.manager_create_project, name='manager-create-project'),

    path('manager-submit-completion-request/', views.manager_submit_completion_request_pro, name='manger_submit_completion_request_pro'),
    # Маршруты для сотрудников

    # path('main-employer/', views.main_employer, name='main-employer'),

    path('employee-main/<str:card>/', views.employee_main, name='employee-main'),
    path('employee-submit-completion-request/', views.employee_submit_completion_request_task,
         name='employee_submit_completion_request_task'),

]

handler404 = 'authentication.views.page_not_found'

pms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from management.views import error_handler
from authentication.views import page_not_found, access_denied

urlpatterns = [
    path('', include('authentication.urls', namespace='authentication')),
    path('mangement/', include('management.urls', namespace='management')),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found
handler403 = access_denied

management/models.py
from django.db import models
from authentication.models import CustomUser
from django.contrib.auth import get_user_model


class Project(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    created_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='created_projects',
                                   verbose_name='Создано')
    assigned_to = models.ManyToManyField(CustomUser, related_name='assigned_projects',
                                         limit_choices_to={'is_manager': True}, blank=True, null=True,
                                         verbose_name='Назначено')
    start_date = models.DateField(null=True, blank=True, verbose_name='Дата начала')
    end_date = models.DateField(null=True, blank=True, verbose_name='Дата окончания')
    project_status = models.CharField(max_length=20, choices=(
        ('not_started', 'Не начат'), ('in_progress', 'В процессе'), ('completed', 'Завершен')), default='not_started',
                                      verbose_name='Статус проекта')
    rating = models.IntegerField(default=0, verbose_name='Рейтинг')
    image = models.ImageField(upload_to="projects/%Y/%m/%d", blank=True, null=True, verbose_name='Изображение')
    approved_by_admin = models.BooleanField(default=False, verbose_name='Одобрено администратором')

    class Meta:
        verbose_name = 'Проекты менеджера'
        verbose_name_plural = 'Проекты менеджеров'

    def __str__(self):
        return self.name


class Task(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='tasks', verbose_name='Проект')
    assigned_to = models.ManyToManyField(CustomUser, related_name='assigned_tasks',
                                         limit_choices_to={'is_employee': True}, verbose_name='Назначено')
    created_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='created_tasks',
                                   limit_choices_to={'is_manager': True}, verbose_name='Создано')
    due_date = models.DateField(null=True, blank=True, verbose_name='Срок выполнения')
    priority = models.IntegerField(choices=((1, 'Low'), (2, 'Medium'), (3, 'High')), default=2,
                                   verbose_name='Приоритет')
    status = models.CharField(max_length=20,
                              choices=(('todo', 'Не начат'), ('inprogress', 'В прогрессе'), ('done', 'Завершено')),
                              default='todo', verbose_name='Статус')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Задача сотрудника"
        verbose_name_plural = "Задачи сотрудников"


class Manager(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    projects = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name='Проекты')
    employees = models.ManyToManyField(CustomUser, related_name='managers', blank=True, verbose_name='Сотрудники')

    def __str__(self):
        return self.user.username


class ProjectCompletionRequest(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='completion_requests',
                                verbose_name='Проект')
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name='Пользователь')
    request_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')
    is_approved = models.BooleanField(default=False, verbose_name='Одобрено')
    description = models.TextField(verbose_name='Описание', blank=True)
    rating = models.IntegerField(verbose_name='Оценка', null=True, blank=True)
    proof = models.FileField(upload_to='proofs/%Y/%m/%d',
                             verbose_name='Доказательство', blank=True)

    class Meta:
        verbose_name = 'Запрос о завершении проекта'
        verbose_name_plural = 'Запросы о завершении проектов'

    def __str__(self):
        return f'{self.project} - {self.user}'

    def approve(self):
        self.is_approved = True
        self.save()

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.is_approved and self.rating is not None:
            self.user.rate = self.rating
            self.project.rating = self.rating

            self.user.save()
            self.project.save()


class TaskCompletionRequest(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='completion_requests',
                             verbose_name='Задача')
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name='Пользователь')
    request_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')
    is_approved = models.BooleanField(default=False, verbose_name='Одобрено')
    description = models.TextField(verbose_name='Описание', null=True)

    class Meta:
        verbose_name = 'Запрос о завершении задачи'
        verbose_name_plural = 'Запросы о завершении задач'

    def __str__(self):
        return f'{self.task} - {self.user}'

    def approve(self):
        self.is_approved = True
        self.save()

management/forms.py
from django import forms
from .models import ProjectCompletionRequest, Project, TaskCompletionRequest, Task
from authentication.models import CustomUser
from django.forms import DateInput


class DatePickerInput(DateInput):
    input_type = 'date'

    def __init__(self, attrs=None, format=None):
        if attrs is None:
            attrs = {}
        attrs['lang'] = 'ru'
        super().__init__(attrs, format)


class ProjectForm(forms.ModelForm):
    name = forms.CharField(label='Название', widget=forms.TextInput(attrs={'class': 'form-control col-12'}))
    description = forms.CharField(label='Описание',
                                  widget=forms.Textarea(attrs={'class': 'form-control form-control-lg'}))
    created_by = forms.ModelChoiceField(queryset=CustomUser.objects.filter(is_superuser=True),
                                        widget=forms.Select(attrs={'class': 'custom-select col-12'}),
                                        label='Для админа',
                                        empty_label=None)
    start_date = forms.DateField(
        widget=DatePickerInput(attrs={'class': 'form-control'}),
        label='Начало'
    )
    end_date = forms.DateField(
        widget=DatePickerInput(attrs={'class': 'form-control'}),
        label='Дэдлайн'
    )
    project_status = forms.ChoiceField(choices=(
        ('not_started', 'Не начат'), ('in_progress', 'В процессе'), ('completed', 'Завершен')),
        widget=forms.Select(attrs={'class': 'custom-select col-12'}), label='Статус проекта'
    )
    image = forms.ImageField(label='Изображение')

    class Meta:
        model = Project
        fields = ['name', 'description', 'created_by', 'start_date', 'end_date', 'project_status', 'image']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['created_by'].empty_label = None
        if self.fields['created_by'].queryset.exists():
            self.fields['created_by'].initial = self.fields['created_by'].queryset.first()

        # self.fields['assigned_to'].queryset = CustomUser.objects.filter(is_manager=True)


class TaskForm(forms.ModelForm):
    name = forms.CharField(label='Задача', widget=forms.TextInput(attrs={'class': 'form-control col-12'}))
    project = forms.ModelChoiceField(queryset=Project.objects.none(), empty_label='Выберете проект',
                                     widget=forms.Select(attrs={'class': 'custom-select col-12'}), label='Проект')
    assigned_to = forms.ModelMultipleChoiceField(queryset=CustomUser.objects.filter(is_employee=True),
                                                 widget=forms.SelectMultiple(
                                                     attrs={'class': 'custom-select col-12', 'size': 10}),
                                                 label='Назначено', to_field_name="last_name")
    due_date = forms.DateField(
        widget=DatePickerInput(attrs={'class': 'form-control'}),
        label='Срок выполнения'
    )
    priority = forms.ChoiceField(choices=((1, 'Легко'), (2, 'Среднее'), (3, 'Сложно')),
                                 widget=forms.Select(attrs={'class': 'custom-select col-12'}), label='Приоритет')
    status = forms.ChoiceField(choices=(('todo', 'Не начать'), ('inprogress', 'В прогрессе'), ('done', 'Закончено')),
                               widget=forms.Select(attrs={'class': 'custom-select col-12'}), label='Статус')
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control form-control-lg', 'rows': 5}),
                                  label='Описание', required=False)

    class Meta:
        model = Task
        fields = ['name', 'description', 'project', 'assigned_to', 'due_date', 'priority', 'status']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user:
            self.fields['project'].queryset = Project.objects.filter(assigned_to=user)
            self.fields['assigned_to'].label_from_instance = lambda obj: f"{obj.last_name} {obj.first_name}"
            self.fields['assigned_to'].widget.attrs['data-live-search'] = 'true'


class ProjectCompletionRequestForm(forms.ModelForm):
    project = forms.ModelChoiceField(queryset=Project.objects.all(), empty_label='Выберете проект',
                                     widget=forms.Select(attrs={'class': 'custom-select col-12'}))
    user = forms.ModelChoiceField(queryset=CustomUser.objects.filter(is_manager=True), empty_label='Выберете менеджера',
                                  widget=forms.Select(attrs={'class': 'custom-select col-12'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control form-control-lg'}),
                                  label='Описание', required=False)

    class Meta:
        model = ProjectCompletionRequest
        fields = ['project', 'user', 'description']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['project'].widget.attrs.update({'class': 'form-control form-control-lg'})
        self.fields['user'].widget.attrs.update({'class': 'form-control form-control-lg'})

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.user = self.cleaned_data['user']
        instance.description = self.cleaned_data['description']
        if commit:
            instance.save()
        return instance


class ProjectCompletionManagerRequestForm(forms.ModelForm):
    project = forms.ModelChoiceField(queryset=Project.objects.all(), empty_label='Выберете проект',
                                     widget=forms.Select(attrs={'class': 'custom-select col-12'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control form-control-lg'}),
                                  label='Описание', required=False)

    class Meta:
        model = ProjectCompletionRequest
        fields = ['project', 'description']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['project'].widget.attrs.update({'class': 'form-control form-control-lg'})


class TaskCompletionRequestForm(forms.ModelForm):
    task = forms.ModelChoiceField(queryset=Task.objects.none(), empty_label='Выберите задачу',
                                  widget=forms.Select(attrs={'class': 'custom-select col-12'}))
    user = forms.ModelChoiceField(queryset=CustomUser.objects.filter(is_employee=True),
                                  empty_label='Выберите сотрудника',
                                  widget=forms.Select(attrs={'class': 'custom-select col-12'}))
    description = forms.CharField(label='Описание', widget=forms.Textarea(attrs={'class': 'form-control'}))

    class Meta:
        model = TaskCompletionRequest
        fields = ['task', 'user', 'description']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        self.fields['task'].queryset = Task.objects.filter(assigned_to=user)
        self.fields['task'].widget.attrs.update({'class': 'form-control form-control-lg'})
        self.fields['user'].widget.attrs.update({'class': 'form-control form-control-lg'})
        if user:
            self.fields['user'].initial = user

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.user = self.cleaned_data['user']
        if commit:
            instance.save()
        return instance

management/templates/management/employee/includes/employee-manage-forms.html
{% if task_create_card %}
    <div class="pd-20 card-box mb-30">
        <div class="clearfix">
            <div class="pull-left">
                <h4 class="text-dark h4">Добавить задачу</h4>
                {#                <p class="mb-30">All bootstrap element classies</p>#}
            </div>
        </div>
        <form method="post">
            {% csrf_token %}
            {% for col in form %}
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label text-lg">{{ col.label }}: </label>
                    <div class="col-sm-12 col-md-10">
                        {{ col }}
                    </div>
                </div>
            {% endfor %}
            <button class="btn btn-primary" type="submit">Задать задачу</button>

        </form>
    </div>

{% endif %}



{% if project_create_card %}
    {% if wait_mess %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Уважаемый {{ request.user.last_name }} {{ request.user.first_name }}!</strong> Ваш проект <span
                class="text-success font-30">{{ project_requested_name }}</span> был предоставлен администратору на
            рассмотрения. Переодический проверяйте эту
            <span><a href="{% url 'management:manager-main' %}" class="text-success font-30"> Ваши проекты </a></span>ссылку
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
        </div>
    {% endif %}
    <div class="pd-20 card-box mb-30">
        <div class="clearfix">
            <div class="pull-left">
                <h4 class="text-dark h4">Запросить проект</h4>
                {#                <p class="mb-30">All bootstrap element classies</p>#}
            </div>
        </div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for col in form %}
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label text-lg">{{ col.label }}: </label>
                    <div class="col-sm-12 col-md-10">
                        {{ col }}
                    </div>
                </div>
            {% endfor %}
            <button class="btn btn-primary" type="submit">Запросить проект</button>

        </form>
    </div>

{% endif %}



{% if sub_pro_card %}
    <div class="pd-20 card-box mb-30">
        <div class="clearfix">
            <div class="pull-left">
                <h4 class="text-dark h4">Доска запросов для завершения проектов</h4>
                {#                <p class="mb-30">All bootstrap element classies</p>#}
            </div>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="form-group row">
                <label class="col-sm-12 col-md-2 col-form-label text-lg">Менеджер</label>
                <div class="col-sm-12 col-md-10">
                    {{ form.user }}
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-12 col-md-2 col-form-label">Проект</label>
                <div class="col-sm-12 col-md-10">
                    {{ form.project }}
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-12 col-md-2 col-form-label">Сопроводительное</label>
                <div class="col-sm-12 col-md-10">
                    {{ form.description }}
                </div>
            </div>

            <button class="btn btn-primary" type="submit">Послать запрос</button>
        </form>


    </div>

{% endif %}

{% if sub_task_card %}
    <div class="pd-20 card-box mb-30">
        <div class="clearfix">
            <div class="pull-left">
                <h4 class="text-dark h4">Доска запросов для завершения проектов</h4>
            </div>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="form-group row">
                <label class="col-sm-12 col-md-2 col-form-label text-lg">Сотрудник</label>
                <div class="col-sm-12 col-md-10">
                    {{ form.user }}
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-12 col-md-2 col-form-label">Задача</label>
                <div class="col-sm-12 col-md-10">
                    {{ form.task }}
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-12 col-md-2 col-form-label">Сопроводительное</label>
                <div class="col-sm-12 col-md-10">
                    {{ form.description }}
                </div>
            </div>

            <button class="btn btn-primary" type="submit">Послать запрос</button>
        </form>


    </div>
{% endif %}

management/templates/management/employee/includes/employee-sidebar.html
{% load static %}
<div class="left-side-bar">
    <div class="brand-logo">
        <a href="">
            <img src="{% static 'vendors/logo_black_lable.svg' %}" alt="" class="dark-logo"/>
            <img
                    src="{% static 'vendors/logo_black_lable.svg' %}"
                    alt=""
                    class="light-logo"/>
        </a>
        <div class="close-sidebar" data-toggle="left-sidebar-close">
            <i class="ion-close-round"></i>
        </div>
    </div>
    <div class="menu-block customscroll">
        <div class="sidebar-menu">
            <ul id="accordion-menu">
                <li>
                    <a href="{% url 'management:employee-main' 'projects' %}" class="dropdown-toggle no-arrow
{% if side_dash %}active{% endif %}">
                        <span class="micon bi bi-house"></span>
                        <span class="mtext">Дашбоард</span>
                    </a>
                </li>


                <li>
                    <a href="{% url 'authenticate:employee-profile' %}"
                       class="dropdown-toggle no-arrow {% if employee_profile %}active{% endif %}">
                        <span class="micon bi bi-person-bounding-box"></span>
                        <span class="mtext">Профиль</span>
                    </a>
                </li>

                <li>
                    <div class="dropdown-divider"></div>
                </li>
                <li>
                    <div class="sidebar-small-cap"></div>
                </li>
                <li>
                    <a href="{% url 'authenticate:logout' %}" class="dropdown-toggle no-arrow">
								<span class="micon bi bi-door-open"></span
                                ><span class="mtext">Выйти</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>