management/urls.py
from django.urls import path
from . import views

from django.conf.urls import handler404
from .views import error_handler

app_name = 'management'

urlpatterns = [
    # Маршруты для администраторов
    path('admin-main/', views.admin_main, name='admin-main'),
    path('admin-managers/', views.admin_managers, name='admin-managers'),
    path('admin-employee/', views.admin_employee, name='admin-employee'),

    path('admin-manage/', views.admin_submit_completion_request, name='admin-manage'),
    path('admin-requests/', views.admin_requests, name='admin-requests'),
    path('admin-subpro/', views.admin_submit_completion_request, name='admin-submit-project'),
    path('admin-subtask/', views.admin_submit_task_completion_request, name='admin-submit-task'),

    path('admin-projects/', views.admin_projects, name='admin-projects'),

    # Маршруты для менеджеров

    path('manager-main/', views.manager_main, name='manager-main'),
    path('manager-emploee/', views.manager_employee, name='manager-employee'),
    path('manager-manage/', views.manager_create_task, name='manager-manage'),

    path('manager-manage-tasks/', views.manager_task_list, name='manager-task-list'),
    path('manager-manage-create-tasks/', views.manager_create_task, name='manager-task-create'),
    path('manager-main-delete-tasks/<int:task_id>/', views.manager_delete_task, name='manager-task-delete'),
    path('manager-main-update-tasks/<int:task_id>/', views.manager_update_task, name='manager-task-update'),
    path('manager-manage-create-project/', views.manager_create_project, name='manager-create-project'),

    path('manager-submit-completion-request/', views.manager_submit_completion_request_pro, name='manger_submit_completion_request_pro'),
    # Маршруты для сотрудников

    # path('main-employer/', views.main_employer, name='main-employer'),

    path('employee-main/<str:card>/', views.employee_main, name='employee-main'),
    path('employee-submit-completion-request/', views.employee_submit_completion_request_task,
         name='employee_submit_completion_request_task'),

]

handler404 = 'authentication.views.page_not_found'

pms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from management.views import error_handler
from authentication.views import page_not_found, access_denied

urlpatterns = [
    path('', include('authentication.urls', namespace='authentication')),
    path('mangement/', include('management.urls', namespace='management')),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found
handler403 = access_denied

management/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from .businesslog.admin import AdminCalculator
from .businesslog.manager import ManagerCalculation
from .models import Project, CustomUser
from .decorators import superuser_required, manager_required
from django.urls import reverse
from .models import ProjectCompletionRequest
from .forms import ProjectCompletionRequestForm, TaskCompletionRequestForm, Task, TaskForm, ProjectForm, \
    ProjectCompletionManagerRequestForm


# Create your views here.
@login_required
@superuser_required
def admin_main(request):
    dryness_list = AdminCalculator.count_dryness()
    projects = AdminCalculator.project_list()
    employees_table = AdminCalculator.user_list()
    # bar_emp_man = AdminCalculator.bar_plot_users(model=CustomUser)

    context = {
        'admin_main': True,
        'employees_count': dryness_list['employees_count'],
        'managers_count': dryness_list['managers_count'],
        'admins_count': dryness_list['admins_count'],
        'project_count': dryness_list['project_count'],
        # 'bar_emp_man': bar_emp_man['bar_emp_man'],
        'projects_table': projects['projects'],
        'managers_table': employees_table['custom_users_managers'],

        'project_card': True,
    }
    return render(request, 'management/admin/admin-main.html', context=context)


@login_required
@superuser_required
def admin_projects(request):
    context = {
        'admin_projects': True,
    }
    return render(request, 'management/admin/admin-secondary.html', context=context)


@login_required
@superuser_required
def admin_managers(request):
    dryness_list = AdminCalculator.count_dryness()
    projects = AdminCalculator.project_list()
    employees_table = AdminCalculator.user_list()

    context = {
        'admin_main': True,
        'employees_count': dryness_list['employees_count'],
        'managers_count': dryness_list['managers_count'],
        'admins_count': dryness_list['admins_count'],
        'project_count': dryness_list['project_count'],

        'managers_table': employees_table['custom_users_managers_top'],

        'manager_card': True,
    }
    return render(request, 'management/admin/admin-main.html', context=context)


@login_required
@superuser_required
def admin_manage(request):
    context = {
        'admin_manage': True,
        'role': 'менеджер',
        'lala': True,

    }
    return render(request, 'management/admin/admin-secondary.html', context=context)


@login_required
@superuser_required
def admin_requests(request):
    context = {
        'admin_manage': True,
        'role': 'менеджер',

    }
    return render(request, 'management/admin/admin-requests.html', context=context)


@login_required
@superuser_required
def admin_submit_completion_request(request):
    if request.method == 'POST':
        form = ProjectCompletionRequestForm(request.POST)
        if form.is_valid():
            completion_request = form.save(commit=False)
            completion_request.user = form.cleaned_data['user']
            completion_request.description = form.cleaned_data['description']
            completion_request.save()
            redirect_url = request.META.get('HTTP_REFERER')
            return redirect(redirect_url)

    else:
        form = ProjectCompletionRequestForm()

    context = {
        'admin_manage': True,
        'role': 'менеджер',
        'sub_pro_card': True,
        'form': form,
    }

    return render(request, 'management/admin/admin-requests.html', context=context)


@login_required
@superuser_required
def admin_submit_task_completion_request(request):
    if request.method == 'POST':
        form = TaskCompletionRequestForm(request.POST)
        if form.is_valid():
            completion_request = form.save(commit=False)
            completion_request.user = form.cleaned_data['user']
            completion_request.description = form.cleaned_data['description']
            completion_request.save()
            redirect_url = request.META.get('HTTP_REFERER')
            return redirect(redirect_url)

    else:
        form = TaskCompletionRequestForm()

    context = {
        'admin_manage': True,
        'role': 'менеджер',
        'sub_task_card': True,
        'form': form,
    }

    return render(request, 'management/admin/admin-requests.html', context=context)


@login_required
@superuser_required
def admin_employee(request):
    dryness_list = AdminCalculator.count_dryness()
    projects = AdminCalculator.project_list()
    employees_table = AdminCalculator.user_list()

    context = {
        'admin_main': True,
        'employees_count': dryness_list['employees_count'],
        'managers_count': dryness_list['managers_count'],
        'admins_count': dryness_list['admins_count'],
        'project_count': dryness_list['project_count'],

        'projects_table': projects['projects'],
        'employees_table': employees_table['custom_users'],
        # 'employee_card': True,
    }
    return render(request, 'management/admin/admin-main.html', context=context)


# managers views
@login_required
@manager_required
def manager_main(request):
    dryness_list = ManagerCalculation.count_dryness(request=request)
    assigned_manager_pro = ManagerCalculation.manager_projects(request=request)
    employees_table = AdminCalculator.user_list()

    context = {
        'manager_main': True,
        'role': 'менеджер',
        'employees_count': dryness_list['employees_count'],
        'project_count': dryness_list['project_count'],
        'tasks_count': dryness_list['tasks_count'],

        'projects_table': assigned_manager_pro['manager_projects'],
        'managers_table': employees_table['custom_users_managers'],

        'project_card': True,
    }
    return render(request, 'management/manager/manager-main.html', context=context)


@login_required
@manager_required
def manager_employee(request):
    dryness_list = ManagerCalculation.count_dryness(request=request)
    assigned_employee = ManagerCalculation.manager_projects(request=request)
    context = {
        'manager_main': True,
        'role': 'менеджер',
        'employees_count': dryness_list['employees_count'],
        'project_count': dryness_list['project_count'],
        'tasks_count': dryness_list['tasks_count'],

        'employees_table': assigned_employee['manager_employees'],

        'employee_card': True,
    }
    return render(request, 'management/manager/manager-main.html', context=context)


# @login_required
# @manager_required
# def manager_manage(request):
#     dryness_list = ManagerCalculation.count_dryness(request=request)
#     projects = AdminCalculator.project_list()
#     employees_table = AdminCalculator.user_list()
#
#     context = {
#         'manager_secondary': True,
#
#         'employees_count': dryness_list['employees_count'],
#         'managers_count': dryness_list['managers_count'],
#         'project_count': dryness_list['project_count'],
#         'tasks_count': dryness_list['tasks_count'],
#
#         'projects_table': projects['projects'],
#         'managers_table': employees_table['custom_users_managers'],
#
#         'project_card': True,
#     }
#     return render(request, 'management/manager/manager-secondary.html', context=context)


@login_required
@manager_required
def manager_create_task(request):
    dryness_list = ManagerCalculation.count_dryness(request=request)

    if request.method == 'POST':
        form = TaskForm(request.POST, user=request.user)  # Передаем текущего пользователя в форму
        if form.is_valid():
            task = form.save(commit=False)
            task.created_by = request.user  # Устанавливаем текущего пользователя как создателя задачи
            form.save()
            return redirect('management:manager-task-list')
    else:
        form = TaskForm(user=request.user)  # Передаем текущего пользователя в форму

    context = {
        'manager_secondary': True,
        'task_create_card': True,
        'project_count': dryness_list['project_count'],
        'employees_count': dryness_list['employees_count'],
        'tasks_count': dryness_list['tasks_count'],

        'form': form,
    }
    return render(request, 'management/manager/manager-secondary.html', context=context)


@login_required
@manager_required
def manager_task_list(request):
    tasks = ManagerCalculation.manager_projects(request=request)
    dryness_list = ManagerCalculation.count_dryness(request=request)
    assigned_employee = ManagerCalculation.manager_projects(request=request)

    context = {
        'manager_main': True,
        'project_count': dryness_list['project_count'],
        'employees_count': dryness_list['employees_count'],
        'tasks_count': dryness_list['tasks_count'],
        'task_card': True,
        'task_list': tasks['task_assigned'],
    }
    return render(request, 'management/manager/manager-main.html', context=context)


@login_required
@manager_required
def manager_delete_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)

    if request.method == 'POST':
        print('hello')
        task.delete()
        return redirect('management:manager-task-list')

    context = {
        'manager-main': True,
        'task_create_card': True,
        'task': task,
    }
    return render(request, 'management/manager/manager-main.html', context=context)


@login_required
@manager_required
def manager_update_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task, user=request.user)
        if form.is_valid():
            form.save()
            return redirect('management:manager-task-list')
    else:
        form = TaskForm(instance=task, user=request.user)

    context = {
        'manager_secondary': True,

management/templates/management/admin/admin-main.html
{% extends 'management/base/base.html' %}
{% load i18n %}
{% load static %}
{% block content %}


    {% include 'management/includes/navbars.html' %}

    {% include 'management/admin/includes/admin-sidebar.html' %}

    <div class="mobile-menu-overlay"></div>

    <div class="main-container">
        <div class="xs-pd-20-10 pd-ltr-20">
            <div class="title pb-20">
                <h2 class="h3 mb-0">Дашбоард администратора</h2>
            </div>
            <div class="row pb-10">

                <div class="col-xl-3 col-lg-3 col-md-6 mb-20">
                    <div class="card-box height-100-p widget-style3">
                        <div class="d-flex flex-wrap">
                            <div class="widget-data">
                                <div class="weight-700 font-24 text-dark">{{ project_count }}</div>
                                <div class="font-14 text-secondary weight-500">
                                    <a href="{% url 'management:admin-main' %}">Проекты</a>
                                </div>
                            </div>
                            <div class="widget-icon">
                                <div class="icon" data-color="#00eccf">
                                    <a class="text-warning" {% url 'management:admin-main' %}> <i
                                            class="icon-copy dw dw-folder-65"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xl-3 col-lg-3 col-md-6 mb-20">
                    <div class="card-box height-100-p widget-style3">
                        <div class="d-flex flex-wrap">
                            <div class="widget-data">
                                <div class="weight-700 font-24 text-dark">{{ managers_count }}</div>
                                <div class="font-14 text-secondary weight-500">
                                    <a href="{% url 'management:admin-managers' %}">Менеджеры</a>
                                </div>
                            </div>
                            <div class="widget-icon">
                                <div class="icon" data-color="#00eccf">
                                    <a class="text-warning" href="{% url 'management:admin-managers' %}"><i
                                            class="icon-copy dw dw-user1"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xl-3 col-lg-3 col-md-6 mb-20">
                    <div class="card-box height-100-p widget-style3">
                        <div class="d-flex flex-wrap">
                            <div class="widget-data">
                                <div class="weight-700 font-24 text-dark">{{ employees_count }}</div>
                                <div class="font-14 text-secondary weight-500">

                                    <a href="{% url 'management:admin-employee' %}">Сотрудники</a>

                                </div>
                            </div>
                            <div class="widget-icon">
                                <div class="icon" data-color="#00eccf">
                                    <a class="text-warning" href="{% url 'management:admin-employee' %}"> <span
                                            class="icon-copy ti-user"></span>
                                    </a></div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xl-3 col-lg-3 col-md-6 mb-20">
                    <div class="card-box height-100-p widget-style3">
                        <div class="d-flex flex-wrap">
                            <div class="widget-data">
                                <div class="weight-700 font-24 text-dark">{{ admins_count }}</div>
                                <div class="font-14 text-secondary weight-500">
                                    <a href="#">Администраторы</a>
                                </div>
                            </div>
                            <div class="widget-icon">
                                <div class="icon" data-color="#00eccf">
                                    <a class="text-warning" href="#"><span class="icon-copy ti-crown"></span></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

{#            {% include 'management/includes/graphics.html' %}#}
            {% include 'management/admin/includes/admin-table.html' %}

            {#            {% include 'management/includes/top.html' %}#}


            <div class="footer-wrap pd-20 mb-20 card-box">
                Квалификационная работа
                Система управления задачами
                - сайт, созданный под руководством Устода Солиева Одилхуджы и Худойбердиева Хуршеда.
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script src="{% static 'vendors/scripts/core.js' %}"></script>
    <script src="{% static 'vendors/scripts/script.min.js' %}"></script>
    <script src="{% static 'vendors/scripts/process.js' %}"></script>
    <script src="{% static 'vendors/scripts/layout-settings.js' %}"></script>
    <script src="{% static 'src/plugins/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static 'src/plugins/datatables/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'src/plugins/datatables/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'src/plugins/datatables/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'src/plugins/datatables/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'vendors/scripts/dashboard3.js' %}"></script>
{% endblock %}

management/templates/management/admin/admin-requests.html
{% extends 'management/base/base.html' %}
{% load i18n %}
{% load static %}
{% block content %}


    {% include 'management/includes/navbars.html' %}

    {#    {% include 'management/includes/sidebar_right.html' %}#}
    {% include 'management/admin/includes/admin-sidebar.html' %}

    <div class="mobile-menu-overlay"></div>

    <div class="main-container">
        <div class="xs-pd-20-10 pd-ltr-20">
            <div class="title pb-20">
                <h2 class="h3 mb-0">Управления запросами</h2>
            </div>
            <div class="row pb-10">

                <div class="col-xl-3 col-lg-3 col-md-6 mb-20">
                    <div class="card-box height-100-p widget-style3">
                        <div class="d-flex flex-wrap">
                            <div class="widget-data">
                                <div class="weight-700 font-24 text-dark">{{ employees_count }}</div>
                                <div class="font-14 text-secondary weight-500">

                                    <a href="{% url 'management:admin-submit-project' %}">Завершит проект</a>

                                </div>
                            </div>
                            <div class="widget-icon">
                                <div class="icon" data-color="#00eccf">
                                    <a class="text-warning" href="{% url 'management:admin-submit-project' %}">
                                        <i class="icon-copy dw dw-suitcase"></i>

                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xl-3 col-lg-3 col-md-6 mb-20">
                    <div class="card-box height-100-p widget-style3">
                        <div class="d-flex flex-wrap">
                            <div class="widget-data">
                                <div class="weight-700 font-24 text-dark">{{ managers_count }}</div>
                                <div class="font-14 text-secondary weight-500">
                                    <a href="{% url 'management:admin-submit-task' %}">Завершит задачи</a>
                                </div>
                            </div>
                            <div class="widget-icon">
                                <div class="icon" data-color="#00eccf">
                                    <a class="text-warning" href="{% url 'management:admin-submit-task' %}">
                                        <i class="icon-copy dw dw-email"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-6 mb-20">
                    <div class="card-box height-100-p widget-style3">
                        <div class="d-flex flex-wrap">
                            <div class="widget-data">
                                <div class="weight-700 font-24 text-dark">{{ project_count }}</div>
                                <div class="font-14 text-secondary weight-500">
                                    <a href="{% url 'admin:authentication_registrationrequest_changelist' %}">Принять в
                                        систему</a>
                                </div>
                            </div>
                            <div class="widget-icon">
                                <div class="icon" data-color="#00eccf">
                                    <a class="text-warning"
                                       href="{% url 'admin:authentication_registrationrequest_changelist' %}">
                                        <i class="icon-copy dw dw-key"></i>
                                    </a>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xl-3 col-lg-3 col-md-6 mb-20">
                    <div class="card-box height-100-p widget-style3">
                        <div class="d-flex flex-wrap">
                            <div class="widget-data">
                                <div class="weight-700 font-24 text-dark">{{ managers_count }}</div>
                                <div class="font-14 text-secondary weight-500">
                                    <a href="#">Фидбэки</a>
                                </div>
                            </div>
                            <div class="widget-icon">
                                <div class="icon" data-color="#00eccf">
                                    <a href="" class="text-warning"> <i class="icon-copy dw dw-edit-1"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-6 mb-20">
                    <div class="card-box height-100-p widget-style3">
                        <div class="d-flex flex-wrap">
                            <div class="widget-data">
                                <div class="weight-700 font-24 text-dark">
                                    {% if employee_count %}{{ employees_count }}{% else %}{% endif %}</div>
                                <div class="font-14 text-secondary weight-500">

                                    <a href="{% url 'admin:management_project_changelist' %}">Проекты</a>

                                </div>
                            </div>
                            <div class="widget-icon">
                                <div class="icon" data-color="#00eccf">
                                    <a class="text-warning" href="{% url 'admin:management_project_changelist' %}"><i
                                            class="icon-copy dw dw-folder-5"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xl-3 col-lg-3 col-md-6 mb-20">
                    <div class="card-box height-100-p widget-style3">
                        <div class="d-flex flex-wrap">
                            <div class="widget-data">
                                <div class="weight-700 font-24 text-dark">
                                    {% if managers_count %}{{ managers_count }}{% else %}{% endif %}</div>
                                <div class="font-14 text-secondary weight-500">
                                    <a href="{% url 'admin:management_task_changelist' %}"> Задачи </a>
                                </div>
                            </div>
                            <div class="widget-icon">
                                <div class="icon" data-color="#00eccf">
                                    <a class="text-warning" href="{% url 'admin:management_task_changelist' %}">
                                       <i class="icon-copy dw dw-add-file-1"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


            </div>

            {#            <div class="title pb-20 pt-20">#}
            {#                <h2 class="h3 mb-0">Доска запросов для завершения проектов</h2>#}
            {#            </div>#}

            {% include 'management/admin/includes/admin-manage-forms.html' %}

            {#            {% include 'management/includes/graphics.html' %}#}
            {#            {% include 'management/includes/admin-table.html' %}#}
            {#            {% include 'management/includes/top.html' %}#}


            <div class="footer-wrap pd-20 mb-20 card-box">
                Квалификационная работа
                Система управления задачами
                - сайт, созданный под руководством Устода Солиева Одилхуджы и Худойбердиева Хуршеда.
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script src="{% static 'vendors/scripts/core.js' %}"></script>
    <script src="{% static 'vendors/scripts/script.min.js' %}"></script>
    <script src="{% static 'vendors/scripts/process.js' %}"></script>
    <script src="{% static 'vendors/scripts/layout-settings.js' %}"></script>
    <script src="{% static 'src/plugins/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static 'src/plugins/datatables/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'src/plugins/datatables/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'src/plugins/datatables/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'src/plugins/datatables/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'vendors/scripts/dashboard3.js' %}"></script>
{% endblock %}

management/templates/management/admin/profile.html
<!-- profile.html -->
{% extends 'management/base/base.html' %}

{% block content %}
    <h2>Profile</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
    <div class="container">
        <div class="row">
            <div class="col-4">
                {% if user.image %}
                    <img src="{{ user.image.url }}" alt="{{ user.username }}"/>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}